import Head from "next/head";
import styles from "../styles/Home.module.css";

import Image from "next/image";
import Link from "next/link";

import { useCollection } from "react-firebase-hooks/firestore";
import { useEffect } from "react";
import { db } from "../config/firebase";

export default function Home() {

  const boldBorderStyle = {
    border: "2px solid black", /* Border properties */
    padding: "10px", /* Padding properties */
  };

  return (
    <div
      className={styles.container}
      style={{

        backgroundImage: "url('https://media.tenor.com/57TRBE6D9C8AAAAC/location-graphics.gif')", // Replace with your image path

        backgroundImage: "url('https://media.tenor.com/57TRBE6D9C8AAAAC/location-graphics.gif')",
        backgroundSize: "cover",
        backgroundPosition: "center",
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={styles.main}
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "flex-start",
        }}
      >
        <h1 className={styles.title}>
          Discover <a>Romania</a>
        </h1>

        <div className={styles.grid} style={{ marginTop: "10%" }}>
          <Link href={"/form"}>
          <div className={styles.card} style={boldBorderStyle}>
              <h2 style={{ color: "black", fontWeight: "bold" }}>Start your dream trip &rarr;</h2>
              <p style={{ color: "black", fontWeight: "bold" }}>
                Tell us about your interests and we can plan your trip for you
              </p>
          </div>
          </Link>
          <Link href={"/map"}>
            <div className={styles.card} style={boldBorderStyle}>
              <h2 style={{ color: "black", fontWeight: "bold" }}>See tourist spots &rarr;</h2>
              <p style={{ color: "black", fontWeight: "bold" }}>
                See a map showing all desirable locations tourists usually visit!
              </p>
            </div>
          </Link>
          <Link href={"/profile_page"}>
            <div className={styles.card} style={boldBorderStyle}>
              <h2 style={{ color: "black", fontWeight: "bold" }}>Profile &rarr;</h2>
              <p style={{ color: "black", fontWeight: "bold" }}>
                Click to open a blank page
              </p>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer} style={{ backgroundColor: "black", padding: "10px", width: "100%", textAlign: "center" }}>
        <span style={{ color: "white" }}>
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </span>
      </footer>
    </div>
  );
}
